import { useRouter } from "next/router";
import Head from "next/head";

const DynamicPage = () => {

    const router = useRouter();
    const {dynamic} = router.query;

    return (
        <div>
            <Head>
                <title>{dynamic}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Dynamic Page {dynamic}</h1>
        </div>
    )
}

export default DynamicPage;