import React from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head';
import Link from 'next/link';

const Course = () => {

    const route = useRouter();
    const {id} = route.query;

  return (
    <div>
        <Head>
            <title>{id}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Course {id}</h1>
        <Link href={'/courses'}>Back to courses</Link>
    </div>
  )
}

export default Course