import React from 'react'
import Head from 'next/head'

const Courses = () => {
  return (
    <div>
        <Head>
            <title>Courses</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>List of Courses</h1>
    </div>
  )
}

export default Courses